version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Web console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /home/infyshine/minio-local/data:/data  # local folder path
    command: server /data --console-address ":9001"
    restart: unless-stopped